### ISSUE TITLE
latest Julia master breakage

### ISSUE THREAD

**Issue by Cody-G** [SimonDanisch/GLPlot.jl#25]
Hi Simon,

This may already be on your radar, but I think the latest julia master has broken some things.  Here's what I get when I try to use GLPlot:

ERROR: LoadError: LoadError: MethodError: `convert` has no method matching convert(::Type{ImmutableArrays.Vector3{Float32}})
This may have arisen from a call to the constructor ImmutableArrays.Vector3{Float32}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  convert{T}(::Type{ImmutableArrays.Vector3{T}}, ::ImmutableArrays.Vector3{T})
  convert{T}(::Type{ImmutableArrays.Vector3{T}}, ::AbstractArray{T,1})
  convert{T}(::Type{T}, ::T)
 in call at /home/cody/.julia/v0.4/GLAbstraction/src/GLUniforms.jl:48
 in include at ./boot.jl:250
 in include_from_node1 at loading.jl:129
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in reload_path at ./loading.jl:153
 in reload at loading.jl:86
while loading /home/cody/.julia/v0.4/GLPlot/src/surface.jl, in expression starting on line 29
while loading /home/cody/.julia/v0.4/GLPlot/src/GLPlot.jl, in expression starting on line 12

I'm not very familiar with macros, so I'm not sure how to fix this myself.

**Comment by SimonDanisch** [comment]
Hi,
this seems to be an error in ImmutableArrays.jl. Quite ironic, first bug in ImmutableArrays since I'm using it, some days ago I almost completed switching it out in favor of GeometryTypes.jl. But the branch is not error free so I can't get rid of ImmutableArrays yet.
I guess we can try to open an issue... I'm a little demotivated to fix it after looking at the related macro code in [generate_arrays.jl](https://github.com/twadleigh/ImmutableArrays.jl/blob/master/src/generate_arrays.jl#L70).
Maybe open an issue over there?

**Comment by Cody-G** [comment]
I see.  I have opened an issue there.  Closing this one.  Thanks!

**Comment by SimonDanisch** [comment]
Thanks a lot! =)
If I have time I'll try to fix the issue at ImmutableArrays ;)

2015-04-04 16:15 GMT+02:00 Cody Greer <notifications@github.com>:
