### ISSUE TITLE
Pb with displayed iso values ?

### ISSUE THREAD

**Issue by edljk** [SimonDanisch/GLPlot.jl#42]
In the example file GLPlot/example/volume.jl I do not understand why the displayed
slices are not modified while playing with the slice indices. Thanks.

**Comment by SimonDanisch** [comment]
Can you be more specific?
This is the expected result:
![output](https://cloud.githubusercontent.com/assets/1010467/23401987/06ff3c64-fdaa-11e6-8acf-575db7e89649.gif)

**Comment by edljk** [comment]
Sorry, I forgot to precise that I initialized the volume array with:

```julia
function volume_data(N)
  vol     = Float32[sin(x/15.0)+sin(y/15.0)+sin(z/15.0) for x=1:N, y=1:N, z=1:N]
  max     = maximum(vol); min     = minimum(vol)
  vol     = (vol .- min) ./ (max .- min)
end
vol = volume_data(128)
```

**Comment by SimonDanisch** [comment]
This is a funny one!
Replace the plot command with:
```Julia
plot = glplot(
        slice, screen = slice_screens[i],
        color_norm = Vec2f0(0, 1),
        camera = :orthographic_pixel
    )
```
I normalize the intensity values with `color_norm` before looking up the color, and color_norm defaults to `(minimum, maximum)`.
Since the slice for one axis only changes by a constant amount, this will not be visible as the constant amount will get normalized away ;)

**Comment by edljk** [comment]
Ah, ok ! Subtile for me, thanks a lot.
